---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: homeautomation
data:
  telegraf.conf: |-
    [[inputs.mqtt_consumer]]
    ## MQTT broker URLs to be used. The format should be scheme://host:port,
    ## schema can be tcp, ssl, or ws.
    servers = ["tcp://raw.event:1883"]

    ## Topics that will be subscribed to.
    topics = [
      "#",
      "/homeassistant/",
      "/homeassistant/#",
      "/rick/",
      "/rick/#",
    ]

    ## The message topic will be stored in a tag specified by this value.  If set
    ## to the empty string no topic tag will be created.
    # topic_tag = "topic"

    ## QoS policy for messages
    ##   0 = at most once
    ##   1 = at least once
    ##   2 = exactly once
    ##
    ## When using a QoS of 1 or 2, you should enable persistent_session to allow
    ## resuming unacknowledged messages.
    # qos = 0

    ## Connection timeout for initial connection in seconds
    # connection_timeout = "30s"

    ## Maximum messages to read from the broker that have not been written by an
    ## output.  For best throughput set based on the number of metrics within
    ## each message and the size of the output's metric_batch_size.
    ##
    ## For example, if each message from the queue contains 10 metrics and the
    ## output metric_batch_size is 1000, setting this to 100 will ensure that a
    ## full batch is collected and the write is triggered immediately without
    ## waiting until the next flush_interval.
    # max_undelivered_messages = 1000

    ## Persistent session disables clearing of the client session on connection.
    ## In order for this option to work you must also set client_id to identity
    ## the client.  To receive messages that arrived while the client is offline,
    ## also set the qos option to 1 or 2 and don't forget to also set the QoS when
    ## publishing.
    # persistent_session = false

    ## If unset, a random client ID will be generated.
    # client_id = ""

    ## Username and password to connect MQTT server.
    # username = "telegraf"
    # password = "metricsmetricsmetricsmetrics"

    ## Optional TLS Config
    # tls_ca = "/etc/telegraf/ca.pem"
    # tls_cert = "/etc/telegraf/cert.pem"
    # tls_key = "/etc/telegraf/key.pem"
    ## Use TLS but skip chain & host verification
    # insecure_skip_verify = false

    ## Data format to consume.
    ## Each data format has its own unique set of configuration options, read
    ## more about them here:
    ## https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_INPUT.md
    # data_format = "influx"
    data_format = "value"
    data_type = "string" # or "float"
    
    [[outputs.influxdb]]
    urls = ["http://homeautomation-influxdb.homeautomation:8086"]
    database = "telegraf"
    
    ## The value of this tag will be used to determine the database.  If this
    ## tag is not set the 'database' option is used as the default.
    # database_tag = ""

    ## If true, the database tag will not be added to the metric.
    # exclude_database_tag = false

    ## If true, no CREATE DATABASE queries will be sent.  Set to true when using
    ## Telegraf with a user without permissions to create databases or when the
    ## database already exists.
    skip_database_creation = true

    ## Name of existing retention policy to write to.  Empty string writes to
    ## the default retention policy.  Only takes effect when using HTTP.
    # retention_policy = ""

    ## Write consistency (clusters only), can be: "any", "one", "quorum", "all".
    ## Only takes effect when using HTTP.
    write_consistency = "any"

    ## Timeout for HTTP messages.
    # timeout = "5s"

    ## HTTP Basic Auth
    # username = "telegraf"
    # password = "metricsmetricsmetricsmetrics"

    ## HTTP User-Agent
    # user_agent = "telegraf"

    ## UDP payload size is the maximum packet size to send.
    # udp_payload = "512B"

    ## Optional TLS Config for use on HTTP connections.
    # tls_ca = "/etc/telegraf/ca.pem"
    # tls_cert = "/etc/telegraf/cert.pem"
    # tls_key = "/etc/telegraf/key.pem"
    ## Use TLS but skip chain & host verification
    # insecure_skip_verify = false

    ## HTTP Proxy override, if unset values the standard proxy environment
    ## variables are consulted to determine which proxy, if any, should be used.
    # http_proxy = "http://corporate.proxy:3128"

    ## Additional HTTP headers
    # http_headers = {"X-Special-Header" = "Special-Value"}

    ## HTTP Content-Encoding for write request body, can be set to "gzip" to
    ## compress body or "identity" to apply no encoding.
    # content_encoding = "identity"

    ## When true, Telegraf will output unsigned integers as unsigned values,
    ## i.e.: "42u".  You will need a version of InfluxDB supporting unsigned
    ## integer values.  Enabling this option will result in field type errors if
    ## existing data has been written.
    # influx_uint_support = false

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf
  namespace: homeautomation
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      volumes:
      - name: telegraf-config-volume
        configMap:
          name: telegraf-config
          items:
          - key: telegraf.conf
            path: telegraf.conf
          defaultMode: 0744
      containers:
      - name: telegraf
        image: telegraf
        volumeMounts:
          - name: telegraf-config-volume
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   labels:
#     app: telegraf
#   name: telegraf
#   namespace: homeautomation
# spec:
#   selector:
#     app: telegraf
#   type: ClusterIP