---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
  namespace: torrent
  labels:
    app: radarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  template:
    metadata:
      labels:
        app: radarr
    spec:
      volumes:
        - name: radarr-config-volume
          persistentVolumeClaim:
            claimName: radarr-config-claim
        - name: radarr-torrent-volume
          persistentVolumeClaim:
            claimName: torrent-data-claim
      containers:
      - name: radarr
        image: linuxserver/radarr
        ports:
        - name: http
          containerPort: 7878
        env:
        - name: TZ
          value: Europe/Amsterdam
        - name: PGID
          value: "1000"
        - name: PUID
          value: "1000"
        volumeMounts:
          - name: radarr-torrent-volume
            mountPath: /downloads
          - name: radarr-config-volume
            mountPath: /config
        #   - name: radarr-config-volume
        #     mountPath: /config/radarr/radarr.conf
        #     subPath: radarr.conf
        #   - name: set-goose-config-volume
        #     mountPath: /goose/set-goose.sh
        #     subPath: set-goose.sh
        #   - name: set-goose-ovpn-volume
        #     mountPath: /etc/openvpn/ro-10.conf
        #     subPath: ro-10.conf
        #   - name: goose-credentials-volume
        #     mountPath: /goose/login.conf
        #     subPath: login.conf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: radarr
  name: radarr
  namespace: torrent
spec:
  ports:
  - name: http
    targetPort: 7878
    port: 80
  selector:
    app: radarr
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarringress
  namespace: torrent
spec:
  rules:
  - host: radarr.bas
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: radarr
            port:
              number: 80

---
apiVersion: v1
kind: Service
metadata:
  name: radarr-lb-service
  namespace: torrent
spec:
  ports:
  - name: http
    port: 80
    targetPort: 7878
  selector:
    app: radarr
  type: LoadBalancer
  loadBalancerIP: 192.168.6.62



---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr-bas
  namespace: torrent
spec:
  issuerRef:
    name: la1r
    kind: ClusterIssuer
  secretName: radarr-bas-tls
  commonName: radarr.bas
  dnsNames:
  - radarr.bas
  - www.radarr.bas
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: radarr-tls
  namespace: torrent
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`radarr.bas`) && PathPrefix(`/`)
    kind: Rule
    services:
    - name: radarr
      port: 80
  tls:
    secretName: radarr-bas-tls