---
# - include_tasks: ufw.yml
# - include_tasks: fail2ban.yml
# - name: Networking / Restart fail2ban and ufw
#   service:
#     name: "{{ item }}"
#     state: restarted
#   with_items:
#     - fail2ban
#     - ufw

- name: Networking / Allow IP Forwarding
  become: yes
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#?net.ipv4.ip_forward='
    line: 'net.ipv4.ip_forward=1'
