---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: influx-event-data-pv
  labels:
    contenttype: "influx-event-data"
spec:
  capacity:
    storage: 30Gi
  storageClassName: local-storage
  persistentVolumeReclaimPolicy: Retain
  accessModes:
  - ReadWriteMany
  local:
    path: /mnt/largehdd/event/influx
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - big-raver