---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-claim
  namespace: monitoring
spec:
  storageClassName: nfs-212
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi