---
- hosts: all
  remote_user: "{{ target_user }}"
  tasks:
      # - name: "new method: install k8s"
      #   shell:  'curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add - && echo "deb http://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list'
      #   args:
      #     executable: /bin/bash

      # - name: DHCP template
      #   template: src=dhcpcd.conf.j2 dest=/etc/dhcpcd.conf mode=0755
      #   backup: yes
      - name: Add an Apt signing key, uses whichever key is at the URL
        apt_key:
          url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
          state: present
          validate_certs: no
      - name: Add kubernetes key to repo
        apt_repository:
            repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
            state: present

      - name: Update apt-get
        command: apt-get update -q 
        become: True
      # - name: Update and upgrade apt packages
      #   apt:
      #     upgrade: yes
      #     update_cache: yes
      #     cache_valid_time: 86400 #One day
        
      - name: Install kubeadm
        command: apt-get install -yq kubeadm

      - name: Remove swap 1/3
        command: swapoff -a
        ignore_errors: yes
      - name: Remove swap 2/3
        command: systemctl disable dphys-swapfile
        ignore_errors: yes
      - name: Remove swap 3/3
        command: apt-get remove dphys-swapfile -y
        ignore_errors: yes
      
      # FIXME: ugly
      - name: Ugly fix for /boot/cmdline.txt
        replace:
            path: /boot/cmdline.txt
            regexp: '(\s+)rootwait(\s+.*)?$'
            replace: '\1rootwait cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 \2'

      
      - name: Reboot the host to reload the changed config
        shell: sleep 10 && /sbin/shutdown -r now 'Rebooting the host to reload the changed config'
        async: 15
        poll: 5
        ignore_errors: yes
      
      - name: Wait for system to become reachable again
        wait_for_connection:
            delay: 30
            timeout: 10
      # - name: "new method: kubeadm config images pull"
      #   shell:  'kubeadm config images pull'
      #   args:
      #     executable: /bin/bash
      - name: "allow kubernetes through ufw"
        shell:  'ufw allow 6443'
        args:
          executable: /bin/bash

        