---
- name: ssh / Disable Password Authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PasswordAuthentication'
    line="PasswordAuthentication no"
    state=present
    backup=yes
  notify:
    - restart ssh
- name: ssh / Enable pubkey Authentication
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PubkeyAuthentication'
    line="PubkeyAuthentication yes"
    state=present
    backup=yes
  notify:
    - restart ssh
- name: ssh / Disable Root Login
  lineinfile:
    dest=/etc/ssh/sshd_config
    regexp='^PermitRootLogin'
    line="PermitRootLogin no"
    state=present
    backup=yes
  notify:
    - restart ssh