---
- name: Update / Update yum
  become: yes
  shell: |
    yum install epel-release -y
    yum update -y

  args:
    executable: /bin/bash
  when: ansible_facts['distribution'] == "CentOSStream"

- name: Update / Update apt
  become: yes
  shell:  'apt-get update -y'
  args:
    executable: /bin/bash
  when: ansible_os_family == 'Debian'