# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: nginx
# spec:
#   selector:
#     matchLabels:
#       app: nginx
#   template:
#     metadata:
#       labels:
#         app: nginx
#     spec:
#       containers:
#       - name: nginx
#         image: nginx:1
#         ports:
#         - name: http
#           containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx
# spec:
#   ports:
#   - name: http
#     port: 80
#     protocol: TCP
#     targetPort: 80
#   selector:
#     app: nginx
#   type: LoadBalancer
  # loadBalancerIP: 192.168.6.101


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - 50centos
---
apiVersion: v1
kind: Service
metadata:
  name: nginx2
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx2
  type: LoadBalancer
  # loadBalancerIP: 192.168.6.101

