
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-221 # IMPORTANT pvc needs to mention this name
provisioner: nfs-221 # name can be anything
reclaimPolicy: Delete
parameters:
  archiveOnDelete: "true"  
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-221-provisioner
  namespace: storage
  labels:
    classCode: "221"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nfs-221-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-221-provisioner
        classCode: "221"
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution :
            nodeSelectorTerms:
            - matchExpressions:
              - key: la1r.storage/221
                operator: In
                values: [ "true" ]
      serviceAccountName: nfs-pod-provisioner-sa # name of service account created in rbac.yaml
      containers:
        - name: nfs-221-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-provisioner-v
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME # do not change
              value: nfs-221 # SAME AS PROVISONER NAME VALUE IN STORAGECLASS
            - name: NFS_SERVER # do not change
              value: 192.168.5.3 # Ip of the NFS SERVER
            - name: NFS_PATH # do not change
              value: /mnt/ssd/tmp # path to nfs directory setup
      volumes:
       - name: nfs-provisioner-v # same as volume mounts name
         nfs:
           server: 192.168.5.3
           path: /mnt/ssd/tmp
