---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ha-remote-backup-script
  namespace: backup
data:
  ha-remote-backup.sh: |-
    #!/bin/sh
    apk add rsync
    rsync --archive --compress --no-perms --no-owner --no-group --delete --force --update --progress /original/ha/ /mirror/ha/
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ha-remote-backup
  namespace: backup
  labels:
    app: ha-remote-backup
spec:
  schedule: "5 2 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: ha-remote-backup
        spec:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution :
                nodeSelectorTerms:
                - matchExpressions:
                  - key: externalvpn
                    operator: In
                    values: [ "true" ]
          restartPolicy: Never    
          volumes:
          - name: ha-data-volume
            persistentVolumeClaim:
            nfs: 
              server: 192.168.5.1
              path: /mnt/hdd/ha
              readOnly: true
          - name: ha-data-mirror-volume
            nfs: 
              server: 10.8.0.4
              path: /mnt/hdd/ha
          - name: ha-remote-backup-script-volume
            configMap:
              name: ha-remote-backup-script
              items:
              - key: ha-remote-backup.sh
                path: ha-remote-backup.sh
              defaultMode: 0744
          containers:
          - name: ha-remote-backup
            image: alpine:latest
            resources:
              limits:
                cpu: 500m
                memory: 1028Mi
              requests:
                cpu: 50m
                memory: 128Mi
            command: 
              - /ha-remote-backup-script/ha-remote-backup.sh
            volumeMounts:
              - name: ha-data-volume
                mountPath: /original/ha
              - name: ha-data-mirror-volume
                mountPath: /mirror/ha
              - name: ha-remote-backup-script-volume
                mountPath: /ha-remote-backup-script
   