---
- name: Install Openvpn / iptables-persistent
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items: 
    - iptables-persistent
  when: ansible_facts['distribution'] == "CentOSStream"

- name: Install Openvpn / iptables-persistent
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - iptables-persistent

- name: Install Openvpn / Copy iptables config
  become: yes
  template: 
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    mode: "0755"